name: lint

on:
  push:
    branches:
      -dev*

jobs:
  flake8_py3:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.8
      - name: install pipenv
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv

      - name: install packages
        run: pipenv install --dev
      
      - name: run flake8
        run: |
          pipenv run flake8