name: test

on:
  push:
    branches:
      - dev_ci

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install python by pyenv
        run: |
          git clone https://github.com/pyenv/pyenv.git ~/.pyenv
          echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc
          echo 'command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc
          echo 'eval "$(pyenv init -)"' >> ~/.bashrc
          exec "$SHELL"
          pyenv install 3.10.8

      - name: install python
        run: |
            sudo add-apt-repository ppa:deadsnakes/ppa
            sudo apt install python3.10

      - name: install pipenv
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
      
      - name: install mecab etc..
        run: |
          sudo apt install mecab libmecab-dev mecab-ipadic-utf8 git make curl xz-utils file
      
      - name: set neologd
        run: |
          git clone --depth 1 https://github.com/neologd/mecab-ipadic-neologd.git
          cd mecab-ipadic-neologd
          echo yes | ./bin/install-mecab-ipadic-neologd -n
          echo `mecab-config --dicdir`"/mecab-ipadic-neologd"

      
      - name: lock package version
        run: pipenv lock
      
      - name: install packages
        run: pipenv sync --dev
      
      - name: run test
        run: |
          pipenv run pytest