name: test

on:
  push:
    branches:
      - dev_ci

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.8' 
      
      - name: install mecab etc..
        run: |
          sudo apt install mecab libmecab-dev mecab-ipadic-utf8 git make curl xz-utils file
      
      - name: set neologd
        run: |
          git clone --depth 1 https://github.com/neologd/mecab-ipadic-neologd.git
          cd mecab-ipadic-neologd
          echo yes | ./bin/install-mecab-ipadic-neologd -n
          echo `mecab-config --dicdir`"/mecab-ipadic-neologd"

      - name: install packages
        run: pipenv sync --dev
      
      - name: run test
        run: |
          pipenv run pytest